PF-2452 Fix author-username population after sanitize fixes (#448)
After
https://github.com/felleslosninger/github-workflows/pull/435/changes the
update version PR workflow in a CD repo breaks whenever `$PUSHER_NAME`
is empty, as `author-username` was set to the bot user.
`author-username` is used to set assignees on the created PR, but a bot
user cannot be assigned to a PR as reviewer. This reverts back to the
previous behaviour, where the `author-username` always is set to `${{
github.event.pusher.name }}`, even when its empty (which it will be if
the flow was triggered by a bot).

Example breakage:

- App workflow:
https://github.com/eudi-wallet-no/eudiw-verifier-demo/actions/runs/27341027030
- Update version workflow:
https://github.com/felleslosninger/digital-lommebok-cd/actions/runs/27341195690/job/80778173171

This fails with 

```
Error: Assigning agents is not supported with GitHub App installation tokens. Use a user token (personal access token or OAuth token) instead. - https://docs.github.com/rest/issues/assignees#add-assignees-to-an-issue
```

There are probably better ways to properly set these values by using
other GitHub context values, but for now we're going back to the
previous flow to ensure it still works as intended.

---

Other changes:

- Fixed Markdown output table to make it easier to work with in your
editor

---

Testing:

1. Created new workflow in plattform-test-app:
https://github.com/felleslosninger/plattform-test-app/blob/main/.github/workflows/deploy-feature-branch.yml
(using this branch for update image)
2. Pushed up a new branch with no changes (but contains the new
workflow):
https://github.com/felleslosninger/plattform-test-app/tree/PF-2452-branch-for-testing-author-username-fix
3. Triggered a run in this branch via `workflow_dispatch`:
https://github.com/felleslosninger/plattform-test-app/actions/runs/27347622783.
The update image part now sets the following values
<img width="594" height="308" alt="bilde"
src="https://github.com/user-attachments/assets/f99576e6-4025-4fd2-918f-d20d3035fe2e"
/>

4. The update version PR is now merged correctly as the bot user is not
attempted to be added as an assignee on the PR:
https://github.com/felleslosninger/plattform-test-cd/actions/runs/27347830447